server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: changeit
    key-alias: server
  http2:
    enabled: true
security:
  jwt:
    token:
      secret: "erIgagHyflutjakvagBojValOvOtFijOkAkbiteiksipPheybs"
      validity-ms: 900000
